<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
</head>
<body>
<div>
    <form action="/common/common/upload" method="post" enctype="multipart/form-data">
        <input type="file" name="file"/>
        type: <input type="text" name="type" value=""/>
        secret: <input type="text" name="secret" value=""/>
        <input type="submit" value="提交"/>
    </form>
</div>
</body>
</html>