<?php


namespace models\DAO;


use Illuminate\Database\Eloquent\Model;
use Yaf\Registry;

/**
 * @SWG\Swagger(
 *     @SWG\Definition(
 *          type="object",
 *          definition="ruleSingleData",
 *          required={"errno", "errmsg", "data"},
 *          @SWG\Property(property="errno", type="integer", format="int32", description="编码"),
 *          @SWG\Property(property="errmsg", type="string", format="string", description="错误提示信息"),
 *          @SWG\Property(property="result", type="object", ref="#/definitions/ruleSingleObj")
 *     ),
 *     @SWG\Definition(
 *          type="object",
 *          definition="ruleSingleObj",
 *          @SWG\Property(property="data", type="object", ref="#/definitions/ruleSingle")
 *     ),
 *     @SWG\Definition(
 *          type="object",
 *          definition="ruleListData",
 *          required={"errno", "errmsg", "result"},
 *          @SWG\Property(property="errno", type="integer", format="int32", description="编码"),
 *          @SWG\Property(property="errmsg", type="string", format="string", description="错误提示信息"),
 *          @SWG\Property(property="result", ref="#/definitions/ruleListObj"),
 *     ),
 *     @SWG\Definition(
 *          type="object",
 *          definition="ruleListObj",
 *          @SWG\Property(property="data", type="object", ref="#/definitions/ruleData"),
 *          @SWG\Property(property="meta", ref="#/definitions/meta")
 *     ),
 *     @SWG\Definition(
 *          type="array",
 *          definition="ruleData",
 *          @SWG\Items(
 *              title="data", ref="#/definitions/ruleSingle"
 *          )
 *     ),
 *     @SWG\Definition(
 *          type="object",
 *          definition="ruleSingle",
 *          @SWG\Property(property="id", type="integer", format="int32",  description="主键"),
 *          @SWG\Property(property="name", type="string", format="string",  description="权限名称"),
 *          @SWG\Property(property="stats", type="integer", format="int32",  description="状态(0为否,1为是,默认1)"),
 *          @SWG\Property(property="created_by", type="integer", format="int32",  description="创建者"),
 *          @SWG\Property(property="created_at", type="string", format="string",  description="创建时间"),
 *          @SWG\Property(property="updated_by", type="integer", format="int32",  description="更新者"),
 *          @SWG\Property(property="updated_at", type="string", format="string",  description="更新时间"),
 *     )
 * )
 */
class RuleModel extends Model
{
    protected $table = 'rule';
    public $timestamps = false;

    static public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // 执行顺序
        // create: saving,creating,created,saved
        // update: saving,updating,updated,saved

        // 监听update时间
        static::updating(function ($model) {
            if (! in_array('updated_by', array_values($model->getAttributes())))
                $model->updated_by = Registry::get('jwt_info')->id;
        });

        static::creating(function ($model) {
            if (! in_array('created_by', array_values($model->getAttributes())))
                $model->created_by = Registry::get('jwt_info')->id;
            if (! in_array('updated_by', array_values($model->getAttributes())))
                $model->updated_by = Registry::get('jwt_info')->id;
        });

        static::deleting(function ($model) {
            exit(json_encode(get_class_methods($model)));
//            exit(json_encode([get_class($model), $model->id]));
        });
    }

}
